
<!DOCTYPE html>
<html>
<head>
	<title>Menu Utama</title>
</head>
<body>

<table  border="1" align="center">
	<tr>
		<td colspan="3"align="center"><img src="img/header.png" width="500" height="125"></td>
	</tr>

<!- bila mengklik logout akan kembali ke halaman login ->
	<tr>
		<td colspan="3" align="right"><font size="2">SELAMAT DATANG  <a href="index.php">Logout</a></font></td>
	</tr>
	<tr>
		<tr>
		<td colspan="10" align="right"><font size="10"> <tr>   </a></font> </td>
			<tr>
				<tr>
					<tr>
				<tr>
			<tr>
		<tr>
			<tr>
				<tr>
			<br>
	</tr>
	<tr bgcolor="#f5f5da" align="center">
		<td>
			<br>
			<font color="red" size="4">
				Silahkan pilih salah satu!
			</font>
			<br>
			<br>

<!- ke halaman hitung persegi panjang jika di klik ->
			<a href="persegi_panjang.php">
				=>>
					<font color="green" size="2">
						Persegi Panjang
					</font>
				<<=
			</a>
			<br>
			<br>

<!- ke halaman hitung persegi jika di klik ->
			<a href="persegi.php">
				=>>
					<font color="green" size="2">
						Persegi
					</font>
				<<=
			</a>
			<br>
			<br>

<!- ke halaman hitung segitiga jika di klik ->
			<a href="segitiga.php">
				=>>
					<font color="green" size="2">
						Segitiga
					</font>
				<<=
			</a>
			<br>
			<br>
		</td>
	</tr>
</table>

</body>
</html>